# Generated by Django 3.2.4 on 2021-06-06 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='User telegram id')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(max_length=15, verbose_name="User's first name")),
                ('last_name', models.CharField(max_length=15, verbose_name="User's last name")),
                ('phone', models.CharField(max_length=12, verbose_name='Phone number')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('is_active', models.BooleanField(verbose_name='User is active?')),
                ('ban', models.BooleanField(verbose_name='Banned')),
            ],
            options={
                'verbose_name': 'User registered in the bot',
                'verbose_name_plural': 'Users registered in the bot',
            },
        ),
    ]
