# Generated by Django 3.2.4 on 2021-06-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(max_length=15, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(max_length=15, verbose_name='Last name'),
        ),
    ]
