# Generated by Django 3.2.4 on 2021-06-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_botuser_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(max_length=15, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(max_length=15, null=True, verbose_name='Last name'),
        ),
    ]
