# Generated by Django 3.2.4 on 2021-06-06 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='edited_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Edited date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Posted date'),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Blog name')),
                ('articles', models.ManyToManyField(to='bot.Article', verbose_name='Articles in the blog')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Blog owner')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
