# Generated by Django 3.2.3 on 2021-05-25 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='edited_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 17, 52, 45, 458238, tzinfo=utc), verbose_name='Edited date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 17, 52, 45, 458123, tzinfo=utc), verbose_name='Posted date'),
        ),
    ]
