# Generated by Django 3.2.3 on 2021-05-25 17:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20210525_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='edited_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 17, 53, 8, 721713, tzinfo=utc), verbose_name='Edited date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 17, 53, 8, 721643, tzinfo=utc), verbose_name='Posted date'),
        ),
    ]
