# Generated by Django 3.2.4 on 2021-07-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_blogsubscribers_subscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsubscribers',
            name='blog',
        ),
        migrations.AddField(
            model_name='blogsubscribers',
            name='blog',
            field=models.ManyToManyField(to='bot.Blog', verbose_name='Blog'),
        ),
    ]
