# Generated by Django 3.2.4 on 2021-06-06 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0004_rename_subscribers_blogsubscribers_subscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogsubscribers',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'Blog subscribers'},
        ),
        migrations.AlterField(
            model_name='blogsubscribers',
            name='subscriber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Blog subscriber'),
        ),
    ]
