# Generated by Django 3.2.4 on 2021-06-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20210606_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(max_length=3, to='bot.Category', verbose_name="Blog's category"),
        ),
        migrations.AlterField(
            model_name='blog',
            name='articles',
            field=models.ManyToManyField(null=True, to='bot.Article', verbose_name='Articles in the blog'),
        ),
    ]
