# Generated by Django 3.2.4 on 2021-06-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20210606_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='articles',
            field=models.ManyToManyField(to='bot.Article', verbose_name='Articles in the blog'),
        ),
    ]
