# Generated by Django 3.2.4 on 2021-06-14 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_botuser_ban'),
        ('bot', '0008_auto_20210614_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.blog', verbose_name='Blog'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.botuser', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.category', verbose_name='Category'),
        ),
    ]
