# Generated by Django 3.2.4 on 2021-06-18 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_botuser_ban'),
        ('bot', '0010_alter_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsubscribers',
            name='subscriber',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='users.botuser', verbose_name='Blog subscriber'),
        ),
    ]
