# Generated by Django 3.2.4 on 2021-06-18 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_botuser_ban'),
        ('bot', '0011_alter_blogsubscribers_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(max_length=3, related_name='categories', to='bot.Category', verbose_name="Blog's category"),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='users.botuser', verbose_name='Blog owner'),
        ),
        migrations.AlterField(
            model_name='blogsubscribers',
            name='subscriber',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogsubscribers', to='users.botuser', verbose_name='Blog subscriber'),
        ),
    ]
