# Generated by Django 3.2.4 on 2021-06-20 15:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_botuser_ban'),
        ('bot', '0012_auto_20210618_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='botusers', to='users.botuser', verbose_name='Blog owner'),
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(verbose_name='Article views')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.article', verbose_name='Article')),
            ],
        ),
    ]
