# Generated by Django 3.2.4 on 2021-06-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20210620_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleview',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Article views'),
        ),
    ]
